version: '3'
services:
  php:
    container_name: remote_commander
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LOCAL_UID: ${LOCAL_UID}
        LOCAL_GID: ${LOCAL_GID}
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./src:/var/www/html